# permissions for end users to view lives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: live-viewer-role
rules:
- apiGroups:
  - kuberik.io
  resources:
  - lives
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberik.io
  resources:
  - lives/status
  verbs:
  - get
