# permissions for end users to edit livedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: livedeployment-editor-role
rules:
- apiGroups:
  - kuberik.io
  resources:
  - livedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberik.io
  resources:
  - livedeployments/status
  verbs:
  - get
