# permissions for end users to view livedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: livedeployment-viewer-role
rules:
- apiGroups:
  - kuberik.io
  resources:
  - livedeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberik.io
  resources:
  - livedeployments/status
  verbs:
  - get
