# permissions for end users to edit livedeploymentgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: livedeploymentgroup-editor-role
rules:
- apiGroups:
  - kuberik.io
  resources:
  - livedeploymentgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberik.io
  resources:
  - livedeploymentgroups/status
  verbs:
  - get
