# permissions for end users to edit lives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: live-editor-role
rules:
- apiGroups:
  - kuberik.io
  resources:
  - lives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberik.io
  resources:
  - lives/status
  verbs:
  - get
