---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cd
subjects:
- kind: ServiceAccount
  name: cd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: kuberik.io/v1alpha1
kind: LiveDeployment
metadata:
  name: cd
spec:
  branch: main
  template:
    spec:
      serviceAccountName: cd
      path: config/default
      transformers: deployments/cd/manager/transform
      repository:
        url: https://github.com/kuberik/kuberik.git
        auth:
          secretRef:
            name: github-token
